export const PIXEL_SIZE = 6;
export const MAX_BARS = 8;
export const FOOD = 4800; //Note: One hour and a half in seconds
export const PLAY = 3600; 
export const SLEEP = 7200; //7200 for two hours 
export const CENTER_X = 22; // For 16 * 16 images
export const CENTER_Y = 9; // For 16 * 16 images
export const WIN = 1; // 1 point of happiness per RPS win
export const LOSE = 0.5; // Half a point of happiness per RPS lose
export const DRAW = 0.75; // 3/4 point opf happiness per RPS draw
export const MODE_HOME = "Home";
export const MODE_RPS = "RPS";
export const MODE_CHOICE = "Choice";
export const MODE_STATS = "Stats";
export const MODE_MENU = "Menu";
export const MODE_FEEDING = "Feeding";
export const HAND_PAPER = "paper";
export const HAND_ROCK = "rock";
export const HAND_SCISSORS = "scissors";
export const SLEEP_DECREASE = 2; // Need twice the time to decrease stats when asleep
export const AWAKE_DECREASE = 1;
export const AWAKE_STATE = "Awake";
export const SLEEP_STATE = "Sleeping";
export const RUN_AWAY_STATE = "RunAway";